# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 0cbb555ccb300eafa28306393682a65826357c39a2fd815af46b59cb0fbed79d9286eb00e6e5f2b2397617d80f6fe051d4b8f239f4f6dbfddea2a526f1e58f94

test:
  secret_key_base: ba0eada7e26b895fbca1de26dd1e97e227b4000d4aa510b3689135f49d36ea851e80c27b3dd3ccfceddf2713ffc4663d49e8cb405da3b1ad9d19fd6b6184f6e0

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
